PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS TEACHER (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS COURSE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SECTION (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    section_number TEXT NOT NULL,
    course_id INTEGER NOT NULL,
    teacher_id INTEGER NOT NULL,

    FOREIGN KEY (course_id) REFERENCES COURSE(id),
    FOREIGN KEY (teacher_id) REFERENCES TEACHER(id)
);

CREATE TABLE IF NOT EXISTS STUDENT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    national_id TEXT NOT NULL UNIQUE,
    list_number INTEGER NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS SECTION_STUDENT (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    section_id INTEGER NOT NULL,

    FOREIGN KEY (student_id) REFERENCES STUDENT(id),
    FOREIGN KEY (section_id) REFERENCES SECTION(id),
    UNIQUE(student_id, section_id)
);

CREATE TABLE IF NOT EXISTS SCHEDULE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    day_of_week TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    section_id INTEGER NOT NULL,

    FOREIGN KEY (section_id) REFERENCES SECTION(id)
);

CREATE TABLE IF NOT EXISTS ATTENDANCE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    status TEXT NOT NULL,
    last_updated TEXT NOT NULL,
    student_id INTEGER NOT NULL,

    FOREIGN KEY (student_id) REFERENCES STUDENT(id)
);